### ISSUE TITLE
Login animation config not loading

### ISSUE THREAD

**Issue by pujitm** [agnimurus/timeswap#1]
Usage (`lib/login/login.dart`):
In the `initState` of a StatefulWidget:
```dart
DefaultAssetBundle.of(context)
        .loadString("cfg/login/animation.json")
        .then((config) {
      _log.info('config:\n$config');
      animationConfig = json.decode(config);
    });
```

pubspec.yaml

```yaml
name: timeswap
description: A marketplace for peer-to-peer services in local communities.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  logging: ^0.11.3+2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: 1.6.1

flutter:
  uses-material-design: true

  assets:
   - assets/
   - cfg/
```

Error:

```
E/flutter (24338): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: Unable to load asset: cfg/login/animation.json
E/flutter (24338): #0      PlatformAssetBundle.load (package:flutter/src/services/asset_bundle.dart:221:7)
E/flutter (24338): <asynchronous suspension>
E/flutter (24338): #1      AssetBundle.loadString (package:flutter/src/services/asset_bundle.dart:67:33)
E/flutter (24338): <asynchronous suspension>
E/flutter (24338): #2      CachingAssetBundle.loadString.<anonymous closure> (package:flutter/src/services/asset_bundle.dart:162:56)
E/flutter (24338): #3      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:281:23)
E/flutter (24338): #4      CachingAssetBundle.loadString (package:flutter/src/services/asset_bundle.dart:162:27)
E/flutter (24338): #5      LoginScreenState.initState (package:timeswap/login/login.dart:38:10)
E/flutter (24338): #6      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3846:58)
E/flutter (24338): #7      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
```
